[package]
name = "all-is-cubes"
version = "0.5.0"
authors = ["Kevin Reid <kpreid@switchb.org>"]
edition = "2021"
rust-version = "1.70"
description = "Recursive voxel game engine. Can be used for voxel raytracing."
# TODO: add homepage = "..." when we have one
repository = "https://github.com/kpreid/all-is-cubes"
license = "MIT OR Apache-2.0"
# TODO: revisit categories once it's more settled how useful this is as a game engine
categories = ["games", "graphics", "rendering::engine"]

[package.metadata.docs.rs]
features = ["arbitrary"]

[lib]
# Disable running as benchmark so that the default doesn't interfere with Criterion usage.
bench = false

[[bench]]
name = "block_bench"
harness = false

[[bench]]
name = "chunk_bench"
harness = false

[[bench]]
name = "lighting_bench"
harness = false

[[bench]]
name = "raycast_bench"
harness = false

[[bench]]
name = "raytrace_bench"
harness = false

[[bench]]
name = "space_bench"
harness = false

[features]
default = []
arbitrary = ["dep:arbitrary", "ordered-float/arbitrary"]
threads = ["dep:rayon"]

[dependencies]
arbitrary = { workspace = true, optional = true }
base64 = { workspace = true } # used in serialization
bitflags = { workspace = true }
bytemuck = { workspace = true, features = ["derive", "extern_crate_std"] } # derive used in serialization
cgmath = "0.18.0"
downcast-rs = "1.2.0"
embedded-graphics = "0.8.0"
exhaust = { workspace = true }
flate2 = { version = "1.0.26" }
futures-core = { workspace = true }
# image is used for its common image data types (for HeadlessRenderer),
# and for PNG asset loading.
image = { workspace = true, features = ["png"] }
indoc = { workspace = true }
instant = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
mutants = { workspace = true }
num-traits = { workspace = true }
once_cell = { workspace = true }
ordered-float = { workspace = true }
rand = { workspace = true }
rand_xoshiro = { workspace = true }
rayon = { workspace = true, optional = true }
# std and rc features needed because we are [de]serializing `Arc`s
serde = { workspace = true, features = ["derive", "std", "rc"] }
serde_repr = { version = "0.1.12", default-features = false }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
# Using tokio for async test-running.
tokio = { workspace = true, features = ["macros", "rt", "sync"] }

